baseURL = 'https://blognivins.netlify.app/'
languageCode = 'en-us'
title = 'The NS'
theme = "beautifulhugo"
pygmentsStyle = "trac"


[Params]
 homeTitle = "Nivin Blogs" 
  subtitle = "Welcome to My Blog site ğŸ‘‹"
  logo = "img/Me_Logo.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "April 20 2023"
  wordCount = true
  rss = true
  readingTime = true
  showRelatedPosts = true


[Author]
 name = "Nivin S"
 github = "https://github.com/Nivin389"
 website = "https://nivins.in/"
 twitter = "https://twitter.com/Nivin389"
 instagram = "https://www.instagram.com/vin._.xil/"
 spotify = "https://open.spotify.com/user/j0u77uc3cgfpkknhv10c3v32o"
 discord = "YWsCyzecDR"
 email = "nivinsvysakh2023@gmail.com"



[[menu.main]]
    name = "ğŸ¡ home"
    url = ""
    weight = 1


[[menu.main]]
    name = "ğŸ˜ About"
    url = "page/aboutme"
    weight = 3


[[menu.main]]
    name = "ğŸ˜‹ Fan Arts!"
    url = "page/fanarts"
    weight = 3


 [[menu.main]]
    identifier = "samples"
    name = "ğŸ“° All Blogs"
    weight = 2

[[menu.main]]
    name = "ğŸ§¤ Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    parent = "samples"
    name = "ğŸ¥½ Favicon"
    url = "posts/favicon"
    weight = 1



[[menu.main]]
    parent = "samples"
    name = "ğŸ˜ HackDino"
    url = "posts/hackclub-dino"
    weight = 1


[[menu.main]]
    parent = "samples"
    name = "ğŸ“ƒ CLI"
    url = "posts/cli-terminal"
    weight = 1



