baseURL = 'https://blognivins.netlify.app/'
languageCode = 'en-us'
title = 'Nivin Vysakh'
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"


[Params]
 homeTitle = "Nivin Blogs" 
  subtitle = "Welcome to My Blog site ğŸ‘‹"
  mainSections = ["post","posts"]
  logo = "img/profile.png"
  favicon = "img/icon.png"
  dateFormat = "January 2, 2006"
  wordCount = true
  rss = false
  readingTime = true
  showRelatedPosts = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  hideAuthor = true


[Author]
 name = "Nivin S"
 github = "https://github.com/ilynivin"
 codepen = "https://codepen.io/Nivin389"
 website = "https://nivins.in/"
 twitter = "https://twitter.com/Nivin389"
 instagram = "https://www.instagram.com/vin._.xil/"
 spotify = "https://open.spotify.com/user/j0u77uc3cgfpkknhv10c3v32o"
 discord = "YWsCyzecDR"
 email = "nivinsvysakh2023@gmail.com"



[[menu.main]]
    name = "ğŸ¡ home"
    url = ""
    weight = 1


[[menu.main]]
    name = "ğŸ˜‹ Fan Arts!"
    url = "page/fanarts"
    weight = 3
 [[menu.main]]
    identifier = "samples"
    name = "ğŸ“° All Blogs"
    weight = 2
[[menu.main]]
    name = "ğŸ§¤ Tags"
    url = "tags"
    weight = 3
[[menu.main]]
    parent = "samples"
    name = "ğŸ¥½ Favicon"
    url = "posts/favicon"
    weight = 1
[[menu.main]]
    parent = "samples"
    name = "ğŸŒ Astro"
    url = "posts/switch-to-astro"
    weight = 1
[[menu.main]]
    parent = "samples"
    name = "ğŸ“ƒ HTML Basics"
    url = "posts/html-basics"
    weight = 1
[[menu.main]]
    parent = "samples"
    name = "âš™ CLI"
    url = "posts/cli-terminal"
    weight = 1
[[menu.main]]
    parent = "samples"
    name = "ğŸ’˜ Hugo"
    url = "posts/start-creating-hugo"
    weight = 1

