baseURL = 'https://blognivins.netlify.app/'
languageCode = 'en-us'
title = 'Nivin Blogs'
theme = "beautifulhugo"
pygmentsStyle = "trac"


[Params]
# homeTitle = "Nivin's Blog" # Set a different text for the header on the home page
  subtitle = "Welcome to My Blog site ğŸ‘‹"
  logo = "img/logo.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "April 20 2023"
  wordCount = true

 [Author]
 name = "Nivin S"
 github = "https://github.com/Nivin389"
 website = "https://nivins.in/"
 twitter = "https://twitter.com/Nivin389"
 instagram = "https://www.instagram.com/vin._.xil/"
 spotify = "https://open.spotify.com/user/j0u77uc3cgfpkknhv10c3v32o"



[[menu.main]]
    name = "ğŸ¡ home"
    url = ""
    weight = 1


 [[menu.main]]
    identifier = "samples"
    name = "ğŸ“° All Blogs"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "About-Me"
    url = "posts/aboutme"
    weight = 1

[[menu.main]]
  name = "ğŸ¥¢ Tags"
  url = "tags"
  weight = 3
